### ISSUE TITLE
How do I set ’ly2 schema mount‘ of netopeer-cli?

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#1317]
Hi,
I tested `get-config` via `netopeer-cli`.
```
> get-config --source running --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation/ietf-interfaces-model
ly ERROR: Ext plugin "ly2 schema mount v1": Failed to get extension data, no callback set.
nc ERROR: Received an invalid message (Ext plugin "ly2 schema mount v1": Failed to get extension data, no callback set.).
cli_send_recv: Failed to receive a reply.
```
How do I set ’ly2 schema mount‘ of netopeer-cli?

**Comment by michalvasko** [comment]
You must provide the `ietf-yang-library` and `ietf-yang-schema-mount` operational data in a file, set it using the `ext-data` command.

**Comment by rydy** [comment]
> You must provide the `ietf-yang-library` and `ietf-yang-schema-mount` operational data in a file, set it using the `ext-data` command.

Is the `--path` is invalid？

```
> ext-data -h
ext-data [--help] [--path <file>]
> ext-data --path
cmd_extdata: Unable to access file "--path" (No such file or directory).
> ext-data --path /root/yangr/O1/testcase/TestcaseOfSysrepoForO-DU/ietf-yang-schema-mount.xml
cmd_extdata: Unable to access file "--path" (No such file or directory).
> ext-data --path=/root/yangr/O1/testcase/TestcaseOfSysrepoForO-DU/ietf-yang-schema-mount.xml
cmd_extdata: Unable to access file "--path=/root/yangr/O1/testcase/TestcaseOfSysrepoForO-DU/ietf-yang-schema-mount.xml" (No such file or directory).
> ext-data --path/root/yangr/O1/testcase/TestcaseOfSysrepoForO-DU/ietf-yang-schema-mount.xml
cmd_extdata: Unable to access file "--path/root/yangr/O1/testcase/TestcaseOfSysrepoForO-DU/ietf-yang-schema-mount.xml" (No such file or directory).
> ext-data --path /root/yangr/O1/testcase/TestcaseOfSysrepoForO-DU/ietf-yang-schema-mount.xml
cmd_extdata: Unable to access file "--path" (No such file or directory).

```

I tried setting ietf-yang-schema-mount.xml, The following log has occurred.

```
> user-rpc --content aggregation-reset-interface-counters.xml --rpc-timeout 30
ly ERROR: Ext plugin "ly2 schema mount v1": Failed to get extension data, no callback set.
nc ERROR: Failed to create RPC, perhaps a required feature is disabled.
cli_send_recv: Failed to send the RPC.
> ext-data /root/yangr/O1/testcase/TestcaseOfSysrepoForO-DU/ietf-yang-schema-mount.xml
> user-rpc --content aggregation-reset-interface-counters.xml --rpc-timeout 30
ly ERROR: Data model "sysrepo@2021-10-08" not found in local searchdirs.
ly ERROR: Loading "sysrepo" module failed. (Data location "/o-ran-aggregation-base:aggregated-o-ru/aggregation[ru-instance='Baciells_sRU67XXX_B122601202134000326']/o-ran-agg-interfaces:interfaces-model", line number 6.)
ly ERROR: Unable to load module sysrepo@2021-10-08 specified by yang library data.
ly ERROR: Ext plugin "ly2 schema mount v1": Failed to create context for the schema-mount data.
nc ERROR: Failed to create RPC, perhaps a required feature is disabled.
cli_send_recv: Failed to send the RPC.
```

**Comment by michalvasko** [comment]
> Is the `--path` is invalid?

Sorry about that but the help is obviously wrong, no `--path` is actually expected. I am improving schema mount support right now and `ext-data` command will be removed, it will no longer be needed.

> I tried setting ietf-yang-schema-mount.xml, The following log has occurred.

That does seem like a problem, I will try to reproduce it and fix together with the improvements I am doing.

**Comment by rydy** [comment]
> > Is the `--path` is invalid?
> 
> Sorry about that but the help is obviously wrong, no `--path` is actually expected. I am improving schema mount support right now and `ext-data` command will be removed, it will no longer be needed.
> 
> > I tried setting ietf-yang-schema-mount.xml, The following log has occurred.
> 
> That does seem like a problem, I will try to reproduce it and fix together with the improvements I am doing.

Ok, Let me know when it is fixed.
Thanks

**Comment by michalvasko** [comment]
Should now be improved and the specific problem fixed.

**Comment by rydy** [comment]
> Should now be improved and the specific problem fixed.

Ok, I will sync the latest `devel` of the all project.

**Comment by rydy** [comment]
> > Should now be improved and the specific problem fixed.
> 
> I tried to test after updating the latest `devel` of all project.
> 
> **Pre-condition:** Ensure[ o-ran-interfaces](https://gerrit.o-ran-sc.org/r/c/scp/oam/modeling/+/5706/3/data-model/yang/published/o-ran/ru-fh/o-ran-interfaces%25402020-12-10.yang), `o-ran-aggregation-base` , `o-ran-agg-ietf-interfaces` , and `o-ran-agg-interfaces `are installed. o-ran-agg-ietf-interfaces
> 
> ```
> module o-ran-aggregation-base {
>   yang-version 1.1;
>   namespace "urn:o-ran:agg-base:1.0";
>   prefix "or-agg-base";
> 
>   import o-ran-operations {
>     prefix "or-ops";
>   }
> 
> ........
> 
>   typedef ru-ref {
>     type leafref {
>       path "/or-ops:operational-info/or-ops:declarations/or-ops:ru-instance-id";
>     }
>     description
>       "A type defintion for the ru-instance-id. Although the type used in
>       o-ran-operations is only a 'string', this leafref is used to indicate
>       that the type 'ru-ref' is used to encode ru-instance-id values.
> 
>       These will typically have been recovered using the NETCONF client in an
>       O-DU which has a NETCONF session with an O-RU which implements the
>       o-ran-operations.yang model. ";
>   }
> 
>   grouping ru-grouping {
>     list recovered-ru-instance-ids {
>       key ru-instance-id;
>       config false;
>       description
>         "a list of O-RU instance IDs that have  been recovered by an O-DU which
>         either has:
>         i) a NETCONF session with an O-RU using the O-RAN WG4 fronthaul
>         defined NETCONF/YANG interface, or
>         ii) some vendor proprietary scheme for a managed element that integrates
>         both O-DU and O-RU functionality.";
> 
>       leaf ru-instance-id {
>         type ru-ref;
>         config false;
>       }
>     }
>     list aggregation {
>       key ru-instance;
>       description
>         "a list used to aggregate the configuration and operational state of
>         multiple O-RUs.";
> 
>       leaf ru-instance {
>         type leafref {
>           path "/aggregated-o-ru/recovered-ru-instance-ids/ru-instance-id";
>           require-instance false;
>         }
>       }
>     }
>   }
> 
>   container aggregated-o-ru {
>     description
>       "The top level container used to hold all the aggregated information related
>       to a set of O-RUs.";
> 
>     uses ru-grouping;
>   }
> }
> ```
> 
> o-ran-agg-ietf-interfaces
> 
> ```
> module o-ran-agg-ietf-interfaces {
>   yang-version 1.1;
>   namespace "urn:o-ran:agg-ietf-interfaces:1.0";
>   prefix "or-agg-ietf-if";
> 
>   import o-ran-aggregation-base {
>     prefix "agg";
>   }
> 
>   import ietf-yang-schema-mount {
>     prefix "yangmnt";
>   }
> 
> .......
> 
>   augment "/agg:aggregated-o-ru/agg:aggregation" {
>     container ietf-interfaces-model {
>       yangmnt:mount-point "ietf-interfaces-root" {
>         description
>           "Root for ietf-interfaces.yang model supported per O-RU instance";
>       }
>     }
>   }
> }
> ```
> 
> o-ran-agg-interfaces
> 
> ```
> module o-ran-agg-interfaces {
>   yang-version 1.1;
>   namespace "urn:o-ran:agg-interfaces:1.0";
>   prefix "or-agg-int";
> 
>   import o-ran-aggregation-base {
>     prefix "agg";
>   }
> 
>   import ietf-yang-schema-mount {
>     prefix "yangmnt";
>   }
> 
> ......
> 
>   augment "/agg:aggregated-o-ru/agg:aggregation" {
>     container interfaces-model {
>       yangmnt:mount-point "interfaces-root" {
>         description
>           "Root for o-ran-interfaces.yang model supported per O-RU instance";
>       }
>     }
>   }
> }
> ```
> 
> **Post-condition** netopeer2-server -d -c MSG -t 30 -x $CURRENT_DIR/config/schema_mount_extension/ietf-yang-schema-mount.xml ietf-yang-schema-mount.xml
> 
> ```
> <schema-mounts xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-schema-mount">
> 	<mount-point>
> 		<module>o-ran-agg-ietf-interfaces</module>
> 		<label>ietf-interfaces-root</label>
> 		<config>true</config>
> 		<inline/>
> 	</mount-point>
> 	<mount-point>
> 		<module>o-ran-agg-interfaces</module>
> 		<label>interfaces-root</label>
> 		<config>true</config>
> 		<inline/>
> 	</mount-point>
> </schema-mounts>
> ```
> 
> **Test case** 1, Subscribe to `/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-interfaces:interfaces-model/o-ran-interfaces:reset-interface-counters ` via `sr_rpc_subscribe`, The rpc is successfully triggered by `sysrepcfg`,
> 
> ```
> sysrepocfg --rpc=aggregation-reset-interface-counters.xml  -v 3
> [INF] Connection 67 created.
> [INF] Published event "operational get" "/ietf-yang-schema-mount:schema-mounts" with ID 12.
> [INF] Event "operational get" with ID 12 succeeded.
> [INF] Session 470 (user "root", CID 67) created.
> [INF] Published event "rpc" "/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-interfaces:interfaces-model/o-ran-interfaces:reset-interface-counters" with ID 7 priority 0 for 1 subscribers.
> [INF] Event "rpc" with ID 7 priority 0 succeeded.
> [INF] No datastore changes to apply.
> ```
> 
> Failed to trigger rpc through `netopeer2-cli`.
> 
> ```
> user-rpc --content aggregation-reset-interface-counters.xml --rpc-timeout 30
> ly ERROR: Data model "o-ran-wg4-features@2021-12-01" not found in local searchdirs.
> ly ERROR: Loading "o-ran-wg4-features" module failed. (/)
> ly ERROR: Unable to load module o-ran-wg4-features@2021-12-01 specified by yang library data.
> ly ERROR: Ext plugin "ly2 schema mount v1": Failed to create context for the schema-mount data.
> nc ERROR: Failed to create RPC, perhaps a required feature is disabled.
> cli_send_recv: Failed to send the RPC.
> >
> ```
> 
> 2, Subscribe to `/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-interfaces:ietf-interfaces-model/ietf-interfaces:interfaces` via `sr_oper_get_subscribe`, The `sysrepocfg -X -f xml -d operational -x /o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-interfaces:ietf-interfaces-model/ietf-interfaces:interfaces -t 10 -v 3` cannot trigger the callback.
> 
> ```
> sysrepocfg -X -f xml -d operational -x /o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-interfaces:ietf-interfaces-model/ietf-interfaces:interfaces -t 10 -v 3
> [INF] Connection 70 created.
> [INF] Published event "operational get" "/ietf-yang-schema-mount:schema-mounts" with ID 18.
> [INF] Event "operational get" with ID 18 succeeded.
> [INF] Session 552 (user "root", CID 70) created.
> [INF] No datastore changes to apply.
> ```
> 
> 3, Subscribe to `/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-interfaces:ietf-interfaces-model/ietf-interfaces:interfaces` via `sr_module_change_subscribe`, Cannot trigger callback and The following error occurs.
> 
> ```
> sysrepocfg --import=o-ran-agg-ietf-interfaces.xml -d running -t 10 -v 3
> [INF] Connection 71 created.
> [INF] Published event "operational get" "/ietf-yang-schema-mount:schema-mounts" with ID 19.
> [INF] Event "operational get" with ID 19 succeeded.
> [INF] Session 554 (user "root", CID 71) created.
> sysrepocfg error: Data parsing failed
> [INF] No datastore changes to apply.
> ```
> 
> Is there something wrong with my test case?


I have updated the [latest ](https://github.com/CESNET/netopeer2/releases/tag/v2.1.49) of all project, These test cases still fail, Is there a problem with my test ? 

Looking forward to your reply, thank you.

**Comment by michalvasko** [comment]
Firstly, not sure why I have not responded to your previous post, sorry about that. I have tested all these use-cases and now they should all work:

1. The only problem should be that when using *netopeer2-cli*, you need to set its `searchdir` correctly so that all the mounted YANG modules can be found. If you use `.../repository/yang`, you should be fine.
2. You need to create an instance of `/o-ran-aggregation-base:aggregated-o-ru/aggregation` for it to be in the `operational` datastore, otherwise the callback will never be called because its parent does not exist. If you do, it should work (although it did not originally, there was a minor problem in *sysrepo* that should now be fixed).
3. In this case you cannot see the actual problem, which should now be improved in *libyang* and the error correctly printed. But the cause of the error will likely be your mistake, in my case it was non-implemented `iana-if-type` module.

**Comment by rydy** [comment]
> 
Thanks for your response, I have one more question:
I tried to import the data via sysrepocfg.
```
sysrepocfg --import=o-ran-agg-ietf-interfaces.xml -d running -t 10 -v 3
[INF] Connection 5 created.
[INF] EV ORIGIN: "/ietf-yang-schema-mount:schema-mounts" "oper get" ID 4 published.
[INF] EV ORIGIN: "/ietf-yang-schema-mount:schema-mounts" "oper get" ID 4 succeeded.
[INF] Session 39 (user "root", CID 5) created.
libyang error: Invalid identityref "ianaift:ethernetCsmacd" value - identity found in non-implemented module "iana-if-type". (Data location "/o-ran-aggregation-base:aggregated-o-ru/aggregation[ru-instance='Baciells_sRU67XXX_B122601202134000326']/o-ran-agg-ietf-interfaces:ietf-interfaces-model/ietf-interfaces:interfaces/interface[name='eth2-UPlane-VLAN']/type", line number 8.)
sysrepocfg error: Data parsing failed
[INF] No datastore changes to apply.
```
o-ran-agg-ietf-interfaces.xml
```
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>Baciells_sRU67XXX_B122601202134000326</ru-instance>
    <ietf-interfaces-model xmlns="urn:o-ran:agg-ietf-interfaces:1.0">
		<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
		  <interface>
			<name>eth2-UPlane-VLAN</name>
			<type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
			<enabled>true</enabled>
			<ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
			  <enabled>false</enabled>
			</ipv4>
			<vlan-id xmlns="urn:o-ran:interfaces:1.0">5</vlan-id>
			<mac-address xmlns="urn:o-ran:interfaces:1.0">02:11:22:33:44:55</mac-address>
		  </interface>
		</interfaces>
    </ietf-interfaces-model>
  </aggregation>
</aggregated-o-ru>
```

The `iana-if-type` YANG has been successfully installed. I don't understand what "non-implemented iana-if-type module" means?

```
sysrepoctl -l | grep iana-if-type
iana-if-type                  | 2017-01-19 | i     |           |               |            |
```

**Comment by rydy** [comment]
> Firstly, not sure why I have not responded to your previous post, sorry about that. I have tested all these use-cases and now they should all work:
> 
> 1. The only problem should be that when using _netopeer2-cli_, you need to set its `searchdir` correctly so that all the mounted YANG modules can be found. If you use `.../repository/yang`, you should be fine.
> 2. You need to create an instance of `/o-ran-aggregation-base:aggregated-o-ru/aggregation` for it to be in the `operational` datastore, otherwise the callback will never be called because its parent does not exist. If you do, it should work (although it did not originally, there was a minor problem in _sysrepo_ that should now be fixed).
> 3. In this case you cannot see the actual problem, which should now be improved in _libyang_ and the error correctly printed. But the cause of the error will likely be your mistake, in my case it was non-implemented `iana-if-type` module.

1. I have set `searchpath` of the `netopeer2-cli`, but this problem still exists.
```
> searchpath
/root/yangr/O1/bin/O-DU/Baicells_O-DU_O1/sysrepo_repository/yang/
>
> searchpath
/root/yangr/O1/bin/O-DU/Baicells_O-DU_O1/sysrepo_repository/yang/
> get --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/*
ly ERROR: Data model "o-ran-wg4-features@2021-12-01" not found in local searchdirs.
ly ERROR: Loading "o-ran-wg4-features" module failed. (/)
ly ERROR: Unable to load module o-ran-wg4-features@2021-12-01 specified by yang library data.
ly ERROR: Ext plugin "ly2 schema mount v1": Failed to create context for the schema-mount data.
nc ERROR: Received an invalid message (Ext plugin "ly2 schema mount v1": Failed to create context for the schema-mount data.).
cli_send_recv: Failed to receive a reply.
>
```

**Comment by michalvasko** [comment]
1. You just have to disconnect and create a new session, existing sessions are never modified in any way. However, I have reproduced the problem with the RPC and there were some other problems as well. They should now all be fixed in current *sysrepo*, I have successfully executed the RPC using NETCONF.
2. Pay attention to the `i` in the falgs of the module. It means (legends at the end) that it is only imported, not installed. So install it, and it will work.

**Comment by rydy** [comment]
> 1. You just have to disconnect and create a new session, existing sessions are never modified in any way. However, I have reproduced the problem with the RPC and there were some other problems as well. They should now all be fixed in current _sysrepo_, I have successfully executed the RPC using NETCONF.
> 2. Pay attention to the `i` in the falgs of the module. It means (legends at the end) that it is only imported, not installed. So install it, and it will work.

I see, these use cases have been passed on the `devel`, I have a new question about `notification`.
The netopeer-cli can receive notification of the 'hardware-state-change'.
netopeer2-server.log
```
[DBG]: LN: Session 2: Sending message:
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime>2023-01-31T21:18:27.670951952-05:00</eventTime><hardware-state-change xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware"/></notification>

[DBG]: LN: Session 2: Sending message:
```
netopeer2-cli.log
```
> subscribe
OK
>
>
notification (2023-01-31T21:18:15.572196365-05:00)
<hardware-state-change xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware"/>

>
```
**The same test step and the netopeer-cli can't receive notification of the `hardware-state-change` in `o-ran-agg-ietf-hardware`.**
Key log:
```
[INF] There are no subscribers for "o-ran-aggregation-base" notifications.
[2023-01-31 21:18:27.669][YangDataStore][info][thread 65874] SYSREPO: There are no subscribers for "o-ran-aggregation-base" notifications.
[2023-01-31 21:18:27.669][YangDataStore][debug][thread 65874] Session 156 completed send notif
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
    <aggregation>
        <ru-instance>Baciells_sRU67XXX_B122601202134000326</ru-instance>
        <ietf-hardware-model xmlns="urn:o-ran:agg-ietf-hardware:1.0">
            <hardware-state-change xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
            </hardware-state-change>
        </ietf-hardware-model>
    </aggregation>
</aggregated-o-ru>
```

o-ran-agg-ietf-hardware.yang

```
module o-ran-agg-ietf-hardware {
  yang-version 1.1;
  namespace "urn:o-ran:agg-ietf-hardware:1.0";
  prefix "or-agg-ietf-hw";

  import o-ran-aggregation-base {
    prefix "agg";
  }

  import ietf-yang-schema-mount {
    prefix "yangmnt";
  }

 ......

  augment "/agg:aggregated-o-ru/agg:aggregation" {
    container ietf-hardware-model {
      yangmnt:mount-point "ietf-hardware-root" {
        description
          "Root for ietf-hardware.yang model supported per O-RU instance";
      }
    }
  }
}


```

**Comment by rydy** [comment]
> Fine, update _sysrepo_ and _netopeer2_ and the notifications should work as well.

This user-case has been passed.

**Comment by rydy** [comment]
I tried subscribing to changes of multiple different nodes(`o-ran-agg-ietf-interfaces:ietf-interfaces-model` and `o-ran-agg-ietf-hardware:ietf-hardware-model`) in the same YANG model(`o-ran-aggregation-base`), 
Then I edited `o-ran-agg-ietf-interfaces:ietf-interfaces-model` data via sysrepocfg, 
```
 sysrepocfg --edit=o-ran-agg-ietf-interfaces.xml -d running -t 10 -v 3
[INF] Connection 3 created.
[INF] EV ORIGIN: "/ietf-yang-schema-mount:schema-mounts" "oper get" ID 2 published.
[INF] EV ORIGIN: "/ietf-yang-schema-mount:schema-mounts" "oper get" ID 2 succeeded.
[INF] Session 38 (user "root", CID 3) created.
[INF] EV ORIGIN: "o-ran-aggregation-base" "change" ID 1 priority 0 for 2 subscribers published.
[INF] EV ORIGIN: "o-ran-aggregation-base" "change" ID 1 priority 0 succeeded.
[INF] EV ORIGIN: "o-ran-aggregation-base" "done" ID 1 priority 0 for 2 subscribers published.
[INF] EV ORIGIN: "o-ran-aggregation-base" "done" ID 1 priority 0 succeeded.
[INF] No datastore changes to apply.
[root@localhost TestcaseOfSysrepoForO-DU]#
```
o-ran-agg-ietf-interfaces.xml
```
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>Baciells_sRU67XXX_B122601202134000326</ru-instance>
    <ietf-interfaces-model xmlns="urn:o-ran:agg-ietf-interfaces:1.0">
		<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
		  <interface>
			<name>eth2-UPlane-VLAN</name>
			<type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
			<enabled>true</enabled>
			<ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
			  <enabled>false</enabled>
			</ipv4>
			<vlan-id xmlns="urn:o-ran:interfaces:1.0">5</vlan-id>
			<mac-address xmlns="urn:o-ran:interfaces:1.0">02:11:22:33:44:55</mac-address>
		  </interface>
		</interfaces>
    </ietf-interfaces-model>
  </aggregation>
</aggregated-o-ru>
```
but subscription of the `o-ran-agg-ietf-hardware:ietf-hardware-model` was also triggered.
Key log:
```
[INF] EV LISTEN: "o-ran-aggregation-base" "change" ID 1 priority 0 processing (remaining 2 subscribers).
[2023-02-02 01:07:01.874][YangDataStore][info][thread 93373] SYSREPO: EV LISTEN: "o-ran-aggregation-base" "change" ID 1 priority 0 processing (remaining 2 subscribers).
[2023-02-02 01:07:01.874][YangDataStore][trace][thread 93373] static int baicells::YangDataStoreForSysrepo::OnModuleChangeCallback(sr_session_ctx_t*, uint32_t, const char*, const char*, sr_event_t, uint32_t, void*)
[2023-02-02 01:07:01.875][plugins][trace][thread 93373] baicells::IYangDataStore::ErrorCode baicells::ORanAggHardwareHandler::ModuleChangeHandler(std::string, std::string, baicells::IYangDataStore::Event, std::string&, baicells::IYangDataStore::DataFormat)
[2023-02-02 01:07:01.875][plugins][info][thread 93373] ModuleChange[CHANGE] 'o-ran-aggregation-base'&'/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-hardware:ietf-hardware-model' callback, '/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-hardware:ietf-hardware-model' data:
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>Baciells_sRU67XXX_B122601202134000326</ru-instance>
  </aggregation>
</aggregated-o-ru>

[2023-02-02 01:07:01.875][YangDataStore][trace][thread 93373] static int baicells::YangDataStoreForSysrepo::OnModuleChangeCallback(sr_session_ctx_t*, uint32_t, const char*, const char*, sr_event_t, uint32_t, void*)
[2023-02-02 01:07:01.876][plugins][trace][thread 93373] baicells::IYangDataStore::ErrorCode baicells::ORanAggInterfacesHandler::ModuleChangeHandler(std::string, std::string, baicells::IYangDataStore::Event, std::string&, baicells::IYangDataStore::DataFormat)
[2023-02-02 01:07:01.876][plugins][info][thread 93373] ModuleChange[CHANGE] 'o-ran-aggregation-base'&'/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-interfaces:ietf-interfaces-model' callback, '/o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-ietf-interfaces:ietf-interfaces-model' data:
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>Baciells_sRU67XXX_B122601202134000326</ru-instance>
    <ietf-interfaces-model xmlns="urn:o-ran:agg-ietf-interfaces:1.0">
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface>
          <name>eth2-UPlane-VLAN</name>
          <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
          <enabled>true</enabled>
          <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
            <enabled>false</enabled>
          </ipv4>
          <vlan-id xmlns="urn:o-ran:interfaces:1.0">5</vlan-id>
          <mac-address xmlns="urn:o-ran:interfaces:1.0">02:11:22:33:44:55</mac-address>
        </interface>
      </interfaces>
    </ietf-interfaces-model>
  </aggregation>
</aggregated-o-ru>

[INF] EV LISTEN: "o-ran-aggregation-base" "change" ID 1 priority 0 success (remaining 0 subscribers).
[2023-02-02 01:07:01.877][YangDataStore][info][thread 93373] SYSREPO: EV LISTEN: "o-ran-aggregation-base" "change" ID 1 priority 0 success (remaining 0 subscribers).
[INF] EV LISTEN: "o-ran-aggregation-base" "done" ID 1 priority 0 processing (remaining 2 subscribers).
[2023-02-02 01:07:01.882][YangDataStore][info][thread 93373] SYSREPO: EV LISTEN: "o-ran-aggregation-base" "done" ID 1 priority 0 processing (remaining 2 subscribers).
[2023-02-02 01:07:01.882][YangDataStore][trace][thread 93373] static int baicells::YangDataStoreForSysrepo::OnModuleChangeCallback(sr_session_ctx_t*, uint32_t, const char*, const char*, sr_event_t, uint32_t, void*)
[2023-02-02 01:07:01.885][plugins][trace][thread 93373] baicells::IYangDataStore::ErrorCode baicells::ORanAggHardwareHandler::ModuleChangeHandler(std::string, std::string, baicells::IYangDataStore::Event, std::string&, baicells::IYangDataStore::DataFormat)
[2023-02-02 01:07:01.885][YangDataStore][trace][thread 93373] static int baicells::YangDataStoreForSysrepo::OnModuleChangeCallback(sr_session_ctx_t*, uint32_t, const char*, const char*, sr_event_t, uint32_t, void*)
[2023-02-02 01:07:01.888][plugins][trace][thread 93373] baicells::IYangDataStore::ErrorCode baicells::ORanAggInterfacesHandler::ModuleChangeHandler(std::string, std::string, baicells::IYangDataStore::Event, std::string&, baicells::IYangDataStore::DataFormat)
[INF] EV LISTEN: "o-ran-aggregation-base" "done" ID 1 priority 0 success (remaining 0 subscribers).
[2023-02-02 01:07:01.888][YangDataStore][info][thread 93373] SYSREPO: EV LISTEN: "o-ran-aggregation-base" "done" ID 1 priority 0 success (remaining 0 subscribers).
```
I only edit `o-ran-agg-ietf-interfaces:ietf-interfaces-model` , I don't expect that subscription of the `o-ran-agg-ietf-hardware:ietf-hardware-model` is triggered. what should i do？

**Comment by michalvasko** [comment]
Before I test this, there is a chance it is working as intended. If you have no data and create these
```xml
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>Baciells_sRU67XXX_B122601202134000326</ru-instance>
    <ietf-interfaces-model xmlns="urn:o-ran:agg-ietf-interfaces:1.0">
		<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
		  <interface>
			<name>eth2-UPlane-VLAN</name>
			<type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
			<enabled>true</enabled>
			<ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
			  <enabled>false</enabled>
			</ipv4>
			<vlan-id xmlns="urn:o-ran:interfaces:1.0">5</vlan-id>
			<mac-address xmlns="urn:o-ran:interfaces:1.0">02:11:22:33:44:55</mac-address>
		  </interface>
		</interfaces>
    </ietf-interfaces-model>
  </aggregation>
</aggregated-o-ru>
```
it means you are creating `/o-ran-aggregation-base:aggregated-o-ru/aggregation` list instance (among other nodes). And when default values are being added, all NP containers with their parents are created, which includes `ietf-hardware-model`. `ietf-interfaces-model` is created explicitly in the edit.

**Comment by rydy** [comment]
> 

In this scenario, would it be inefficient if there were a lot of nodes(hundreds of) and every node would be fired?

**Comment by rydy** [comment]
> Before I test this, there is a chance it is working as intended. If you have no data and create these
> 
> ```
> <aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
>   <aggregation>
>     <ru-instance>Baciells_sRU67XXX_B122601202134000326</ru-instance>
>     <ietf-interfaces-model xmlns="urn:o-ran:agg-ietf-interfaces:1.0">
> 		<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
> 		  <interface>
> 			<name>eth2-UPlane-VLAN</name>
> 			<type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
> 			<enabled>true</enabled>
> 			<ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
> 			  <enabled>false</enabled>
> 			</ipv4>
> 			<vlan-id xmlns="urn:o-ran:interfaces:1.0">5</vlan-id>
> 			<mac-address xmlns="urn:o-ran:interfaces:1.0">02:11:22:33:44:55</mac-address>
> 		  </interface>
> 		</interfaces>
>     </ietf-interfaces-model>
>   </aggregation>
> </aggregated-o-ru>
> ```
> 
> it means you are creating `/o-ran-aggregation-base:aggregated-o-ru/aggregation` list instance (among other nodes). And when default values are being added, all NP containers with their parents are created, which includes `ietf-hardware-model`. `ietf-interfaces-model` is created explicitly in the edit.
> 
> To ignore such a change you can either call `sr_get_changes_iter()` with `xpath` that excludes the container (selects only its descendants) or subscribe to the descendants directly.

In this scenario, would it be inefficient if there were a lot of nodes(hundreds of) and every node would be fired?

**Comment by michalvasko** [comment]
> In this scenario, would it be inefficient if there were a lot of nodes(hundreds of) and every node would be triggered(callback handling)?

Yes, it could be. It is up to you to subscribe in a way that this does not occur.

> By the way, Is there an API to get all the changed nodes directly at once?

No, there is not currently. You can only iterate over the changes or get a whole subtree of updated data using standard getters.

**Comment by rydy** [comment]
> 

Ok, i see, thanks.

**Comment by rydy** [comment]
> > In this scenario, would it be inefficient if there were a lot of nodes(hundreds of) and every node would be triggered(callback handling)?
> 
> Yes, it could be. It is up to you to subscribe in a way that this does not occur.
> 
> > By the way, Is there an API to get all the changed nodes directly at once?
> 
> No, there is not currently. You can only iterate over the changes or get a whole subtree of updated data using standard getters.

I want to get changes of the root's `lyd_node`, Which APIs should i use?

**Comment by michalvasko** [comment]
The same API as always, `sr_get_changes_iter()` first with whatever XPath you want to limit the changes and then iterate over them using `sr_get_change_tree_next()`.

**Comment by rydy** [comment]
> The same API as always, `sr_get_changes_iter()` first with whatever XPath you want to limit the changes and then iterate over them using `sr_get_change_tree_next()`.

I know that, I expect to get the root(parent lyd_node) of the changed lyd_node, Instead of fetching changed child nodes one by one, ls there a way ?

**Comment by michalvasko** [comment]
I have already replied.

> By the way, Is there an API to get all the changed nodes directly at once?

> No, there is not currently. You can only iterate over the changes or get a whole subtree of updated data using standard getters.

**Comment by rydy** [comment]
> I have already replied.
> 
> > By the way, Is there an API to get all the changed nodes directly at once?
> 
> > No, there is not currently. You can only iterate over the changes or get a whole subtree of updated data using standard getters.

Ok, thanks.

**Comment by michalvasko** [comment]
Why do I have to keep repeating what I said? No, strictly speaking, there is no API for getting the tree of all the changes. However, an inside note, the changes are actually always in a tree so whatever `node` you get from the changes iterator, it is a part of the whole tree.

**Comment by rydy** [comment]
> 

I see, thanks.
