### ISSUE TITLE
Instance IDs are sent in a wrong format in notifications

### ISSUE THREAD

**Issue by andre-brizido** [CESNET/Netopeer2#519]
When sending a notification using the sysrepo API.
Example:
```
 int rc = 0;
   sr_val_t        values[10] = { { 0, }, };
   size_t          valueCnt = 0;

   values[valueCnt].xpath = "/ietf-alarms:alarm-notification/resource";
   values[valueCnt].type = SR_INSTANCEID_T;
   values[valueCnt].data.instanceid_val = (char *) resource;
   valueCnt++;
   values[valueCnt].xpath = "/ietf-alarms:alarm-notification/alarm-type-id";
   values[valueCnt].type = SR_IDENTITYREF_T;
   values[valueCnt].data.string_val = (char *)type_id;
   valueCnt++;
   values[valueCnt].xpath = "/ietf-alarms:alarm-notification/alarm-type-qualifier";
   values[valueCnt].type = SR_STRING_T;
   values[valueCnt].data.string_val = (char *) type_qualifier;
   valueCnt++;
   values[valueCnt].xpath = "/ietf-alarms:alarm-notification/time";
   values[valueCnt].type = SR_STRING_T;
   values[valueCnt].data.string_val = "2019-07-25T05:51:36+00:00";
   valueCnt++;
   values[valueCnt].xpath = "/ietf-alarms:alarm-notification/alarm-text";
   values[valueCnt].type = SR_STRING_T;
   values[valueCnt].data.string_val =  (char *)alarm_text;
   valueCnt++;
   values[valueCnt].xpath = "/ietf-alarms:alarm-notification/perceived-severity";
   values[valueCnt].type = SR_ENUM_T;
   values[valueCnt].data.enum_val = (char *) severity;
   valueCnt++;

   rc = sr_event_notif_send(session, "/ietf-alarms:alarm-notification", values, valueCnt, SR_EV_NOTIF_EPHEMERAL);
   printf("ietf-alarm notification sent rc=%d\n", rc);
   if (SR_ERR_OK != rc) {
      fprintf(stderr, "Error sending notification: %s\n", sr_strerror(rc));
   }
```
  
When using for example  /ietf-interfaces:interfaces/interface[name='dsl.1'] as the resource string.
The resource appears correctly in the netopeer cli:

```
<alarm-notification xmlns="urn:ietf:params:xml:ns:yang:ietf-alarms">
  <resource xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/if:interfaces/if:interface[if:name=if:dsl.1]</resource>
  <alarm-type-id xmlns:vendor-alarms="urn:vendor:vendor-alarms">vendor-alarms:los</alarm-type-id>
  <alarm-type-qualifier> text </alarm-type-qualifier>
  <time>2019-07-25T05:51:36+00:00</time>
  <alarm-text>link failure</alarm-text>
  <perceived-severity>minor</perceived-severity>
</alarm-notification>
```
But if using another NETCONF client it does not:
```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <eventTime>2020-01-06T16:56:26Z</eventTime>
  <alarm-notification xmlns="urn:ietf:params:xml:ns:yang:ietf-alarms">
    <resource>/ietf-interfaces:interfaces/interface[name=dsl.1]</resource>
    <alarm-type-id xmlns:vendor-alarms="urn:vendor:vendor-alarms">vendor-alarms:los</alarm-type-id>
    <alarm-type-qualifier> text </alarm-type-qualifier>
    <time>2019-07-25T05:51:36+00:00</time>
    <alarm-text>link failure</alarm-text>
    <perceived-severity>minor</perceived-severity>
  </alarm-notification>
</notification>
```

Instead of namespaces the module name is being used.

**Comment by michalvasko** [comment]
Hi,
could you please enable debug messages on the server using `-c MSG` so that the actual message being sent is seen?

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi 

Below is the output. The resource name also appears with the module name instead of namespaces.

```
[INF]: Session 1 received a realtime notification "/ietf-alarms:alarm-notification" (1578441165).
[DBG]: Session 1: sending message:
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime>2020-01-07T23:52:45Z</eventTime><alarm-notification xmlns="urn:ietf:params:xml:ns:yang:ietf-alarms"><resource>/ietf-interfaces:interfaces/interface[name=dsl.1]</resource><alarm-type-id xmlns:vendor-alarms="urn:vendor:vendor-alarms">vendor-alarms:los</alarm-type-id><alarm-type-qualifier> text </alarm-type-qualifier><time>2019-07-25T05:51:36+00:00</time><alarm-text>link failure</alarm-text><perceived-severity>minor</perceived-severity></alarm-notification></notification>

[DBG]: Session 1: sending message:
]]>]]>
```

Best regards
Andre

**Comment by michalvasko** [comment]
Hi Andre,
okay, if you pull the latest `legacy` branch, it should be fixed. But the fix also caused *netopeer2-cli* to not be able to print the value and that is fixed in the latest `devel` *libyang*.

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi
I confirm. The problem is fixed on the server.
Do you have a prevision when there will be a release with this fix?

Thanks.
Best regards
Andre

**Comment by michalvasko** [comment]
Hi Andre,
not sure there will be any. But I suppose once we completely finish the support of this old *netopeer2* and *sysrepo*, there may be a final release.

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi 

It seems that the problem is not completely fixed. Below is the output I get either using code from master, legacy or devel.

The interface name appears as **if:dsl.1** instead of **'dsl.1'**.
```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <eventTime>2020-01-13T14:35:25Z</eventTime>
  <alarm-notification xmlns="urn:ietf:params:xml:ns:yang:ietf-alarms">
    <resource xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/if:interfaces/if:interface[if:name=if:dsl.1]</resource>
    <alarm-type-id xmlns:vendor-alarms="urn:vendor:vendor-alarms">vendor-alarms:los</alarm-type-id>
    <alarm-type-qualifier> text </alarm-type-qualifier>
    <time>2019-07-25T05:51:36+00:00</time>
    <alarm-text>link failure</alarm-text>
    <perceived-severity>minor</perceived-severity>
  </alarm-notification>
</notification>
```

When I use the master or devel branch, I send the notification like this:

```
int rc = 0;
   struct lyd_node *notif = NULL;
   const struct ly_ctx *ctx = sr_get_context(connection);

   notif = lyd_new_path(NULL, ctx, "/ietf-alarms:alarm-notification", NULL, 0, 0);
   if (!notif) {
      fprintf(stderr, "creating notification failed\n");
      goto cleanup;
   }

   fprintf(stderr, "resource=%s type_id=%s\n", resource, type_id);
   if (!lyd_new_path(notif, NULL, "ietf-alarms:resource", (void *) resource, 0, 0)) {
      fprintf(stderr, "tag resource failed: %s val=%s\n", sr_strerror(rc), resource);
      goto cleanup;
   }
   if (!lyd_new_path(notif, NULL, "alarm-type-id", (void *) type_id, 0, 0)) {
      fprintf(stderr, "tag alarm-type-id failed: %s val=%s\n", sr_strerror(rc), type_id);
      goto cleanup;
   }
   if (!lyd_new_path(notif, NULL, "alarm-type-qualifier", (void *) type_qualifier, 0, 0)) {
      fprintf(stderr, "tag alarm-type-qualifie failed: %s val=%s\n", sr_strerror(rc), type_qualifier);
      goto cleanup;
   }
   if (!lyd_new_path(notif, NULL, "time", (void *) "2019-07-25T05:51:36+00:00", 0, 0)) {
      fprintf(stderr, "tag time failed: %s val=%s\n", sr_strerror(rc), "2019-07-25T05:51:36+00:00");
      goto cleanup;
   }
   if (!lyd_new_path(notif, NULL, "alarm-text", (void *)alarm_text, 0, 0)) {
      fprintf(stderr, "tag alarm-text failed: %s val=%s\n", sr_strerror(rc), alarm_text);
      goto cleanup;
   }
   if (!lyd_new_path(notif, NULL, "perceived-severity", (void *)severity, 0, 0)) {
      fprintf(stderr, "tag perceived-severity failed: %s val=%s\n", sr_strerror(rc), severity);
      goto cleanup;
   }

   /* send the notification */
   rc = sr_event_notif_send_tree(session, notif);
   if (rc != SR_ERR_OK) {
       fprintf(stderr, "Error sending notification: %s\n", sr_strerror(rc));
       goto cleanup;
   }

   cleanup:
      lyd_free_withsiblings(notif);

```
In all cases, the resource string is /ietf-interfaces:interfaces/interface[name='dsl.1']

**Comment by michalvasko** [comment]
Hi,
I have tried the current `devel`, this was the notification in *netopeer2-cli*
```xml
notification (2020-01-14T12:46:55Z)
<alarm-notification xmlns="urn:ietf:params:xml:ns:yang:ietf-alarms">
  <resource xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/if:interfaces/if:interface[if:name='dsl.1']</resource>
  <time>2019-07-25T05:51:36+00:00</time>
  <alarm-text>some text</alarm-text>
  <perceived-severity>minor</perceived-severity>
</alarm-notification>
```
and this is the code that sent it (I have removed some attributes from `ietf-alarm` so that I do not have to bother with imports)
```C
    notif = lyd_new_path(NULL, ctx, "/ietf-alarms:alarm-notification", NULL, 0, 0);
    lyd_new_path(notif, NULL, "ietf-alarms:resource", "/ietf-interfaces:interfaces/interface[name='dsl.1']", 0, 0);
    lyd_new_path(notif, NULL, "time", "2019-07-25T05:51:36+00:00", 0, 0);
    lyd_new_path(notif, NULL, "alarm-text", "some text", 0, 0);
    lyd_new_path(notif, NULL, "perceived-severity", "minor", 0, 0);

    rc = sr_event_notif_send_tree(session, notif);
```

The problem is that in your case the interface name, which is supposed to be a literal `'dsl.1'` is actually a node name `if:dsl.1` (no quotes), that is why the prefix is appended. Are you sure you are setting the correct `resource` with the name quoted?

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi Michal

You're right.  The string was not being correctly delivered to lyd_new_path. In my case the resource string is being passed as argument, but the shell was interpreting the quotes.
It's working fine on all branches.

Thanks
Andre
